### ISSUE TITLE
[Task] Clean up bamm-cli interface

### ISSUE THREAD

**Issue by atextor** [OpenManufacturingPlatform/sds-sdk#100]
**Is your task related to a problem? Please describe.**
All of the bamm-cli functionality is currently controlled using a flat list of switches, some of which apply only to one or few actual functions. A best practice for CLIs here is to work with subcommands (cf. eg. git, az cli, kubectl, ...). This should be cleaned up. Here it would make sense to switch from the currently used JCommander to [picocli](https://picocli.info/).

**Describe the solution you'd like**
A clean refactoring/reimplementation of the bamm-cli using picocli; structured with subcommands that make sense, each of which has its own set of switches.

**Comment by RaMisess** [comment]
Proposed structure of the refactored commands/options. Commands/subcommands shown in bold; parameters/options below each command with the preceding "-":

- **help** - new command, will show help for the top level commands and subcommands; -h, --help can still be used to show help for a specific command
- **aspect** - new command grouping all processing related to aspects
   * -i, --input -> all subcommands require as input the Aspect model to work with
   * **html** replaces -html, --generate-documentation
		-d, --output-directory
		-hccf, --html-custom-css-file
   * **diagram** new subcommand grouping all diagram related activities 
		--d, --output-directory
		-svg, --generate-svg-diagram
		-png, --generate-png-diagram
		-dot, --generate-dot-diagram		
   * **json** replaces -json, --generate-json-payload
		-d, --output-directory	
   * **schema** replaces -schema, --generate-json-schema
		-d, --output-directory			
   * **openapi** new subcommand grouping all OpenAPI related stuff
		-d ,--output-directory
		-oapi-json, --generate-openapi-json
		-oapi-yaml, --generate-openapi-yaml			
		-sv, --use-semantic-api-version
		-base-url, --aspect-api-base-url
		-query-api, --include-aspect-query-api
		-arp, --aspect-resource-path
		-apf, --aspect-parameter-file
		-no-paging, --aspect-exclude-paging
		-atbp, --aspect-time-based-paging
		-aobp, --aspect-offset-based-paging
		-acbp, --aspect-cursor-based-paging
   * **java**  new subcommand grouping all Java related stuff, replaces -java, --generate-java-classes, 
		-d, --output-directory
		-pn, --package-name
		-elm, --execute-library-macros
		-tlf, --template-library-file
		-static-java, --generate-static-java-classes
		-dja, --disable-jackson-annotations
   * **validate** replaces -v, --validate, 
   * **migrate**	replaces -m, --migrate
		-d, --output-directory
   * **prettyprint** replaces -p, --pretty-print
		-d, --output-directory

**Comment by atextor** [comment]
Overall I'd agree, but I'd rename some of the switches where the context is now clear by the (sub-)command they are used in, to make them shorter and more memorable:
* In `aspect to html`:
   * `-hccf`, `--html-custom-css-file` to just `-c`,`--css`
* In `aspect to openapi`:
   * `-oapi-json`,`--generate-openapi-json` to `-j`,`--json`
   * `-oapi-yaml`,`--generate-openapi-yaml` to `-y`,`--yaml`
   * `-base-url`,`--aspect-api-base-url` to `-b`,`--api-base-url`
   * `-query-api`,`--include-aspect-query-api` to `-q`,`--include-query-api`
   * `-arp`,`--aspect-resource-path` to `-r`,`--resource-path`
   * `-apf`,`--aspect-parameter-file` to `-p`,`--parameter-file`
   * `-no-paging`,`--aspect-exclude-paging` to `-pn`,`--paging-none`
   * `-atbp`,`--aspect-time-based-paging` to `-pt`,`--paging-time-based`
   * `-aobp`,`--aspect-offset-based-paging` to `-po`,`--paging-offset-based`
   * `-acbp`,`--aspect-cursor-based-paging` to `-pc`,`--paging-cursor-based`
* In `aspect to java`:
   * `--static-java`,`--generate-static-java-classes` to `-s`,`--static`
   * `-dja`,`--disable-jackson-annotations` to `-nj`,`--no-jackson`

I like the proposal to have the input file as a positional parameter of the "aspect" command. I think at some point this should accept either a filename, a URN or "-" (meaning: read from STDIN) (not necessarily inside this story, unless it's trivial to do).

I'm wondering how output should be handled. In most CLIs, without any special options, output is written to STDOUT so you could directly see it on the console or pipe or redirect it. This is also what I'd expect when calling e.g. `bamm aspect MyFile.ttl to json`. But this logic does not work everywhere because:
1. For Java generation, multiple files are written, so `-d`/`--output-directory` makes sense here
2. For diagram generation, currently multiple files can be written (one for each language used in the model), so in the current setup `bamm aspect MyFile.ttl to png` would write MyFile_de.ttl and MyFile_en.ttl (if those two languages are used in the model).
I propose the following: We keep code generation as-is, with the `-d` switch. But the document and diagram generation should just output create one file, so instead of `-d`/`--output-directory` the `html`,`dot`,`png`,`svg`,`json`,`schema` and `openapi` subcommands write to a file by default but should take an optional `-o`/`--output` switch which reads a file name (not a directory name) or "-" for STDOUT. For `html`,`dot`,`png` and `svg`, the generation uses "en" by default als language, but you can override this with a `-l`/`--language` switch. So a few examples how I think it should work:
```sh
bamm aspect MyFile.ttl to html  # writes english docs to MyFile_en.html
bamm aspect MyFile.ttl to html -o Foo.html  # writes english docs to Foo.html
bamm aspect MyFile.ttl to html -l de  # writes german docs to MyFile_de.html
bamm aspect MyFile.ttl to html -l de -o Foo.html  # writes german docs to Foo.html
bamm aspect MyFile.ttl to html -o -  # writes english docs to stdout
bamm aspect MyFile.ttl to html -l de -o - # writes german docs to stdout
# dot, png and svg work similar to html above
# The following commands also know -o  but not -l
bamm aspect MyFile.ttl to json  # writes MyFile.json
bamm aspect MyFile.ttl to json -o sample.json  # writes sample.json
# and so on
```
