### ISSUE TITLE
[BUG] Open Source scanning tools cannot determine licence and copyright

### ISSUE THREAD

**Issue by georgschmidtdumont** [OpenManufacturingPlatform/sds-sdk#134]
**Describe the bug**
Open Source scanning software should be able to determine the correct license and copyright automatically. Currently this is not the case.

**Where**
All SDK components.

**Comment by atextor** [comment]
@georgschmidtdumont Can you please elaborate what needs to be done to support this? As of now, the license file(s) are present in the root directory and are picked up by Github, and every source file has a MPL-2.0 compliant copyright header.

**Comment by georgschmidtdumont** [comment]
@atextor I am not 100% sure. Looking at other open source projects, the license information is included in the POM file. As an example see [Jackson Core](https://github.com/FasterXML/jackson-core/blob/2.14/pom.xml). Maybe this is a possible solution.

I think we need to have a detailed look at where Open Source scanning software expects to find this information.

**Comment by atextor** [comment]
@georgschmidtdumont This is also already the case (and was from the beginning, as this is an OMP requirement), at least for the parent pom: https://github.com/OpenManufacturingPlatform/sds-sdk/blob/main/pom.xml#L28-L32. I would expect third party tools to understand Maven multi module and inheritance semantics, e.g. Maven Central does obviously: https://search.maven.org/artifact/io.openmanufacturing/sds-aspect-meta-model-java/2.0.1/jar - the license is correctly picked up for this artifact even though the license is not explicitly declared in its pom but only in its parent pom. So I'd say it is rather a problem with the third party tool if this does not work. Therefore I'm closing this now, feel free to add more info and reopen.
