### ISSUE TITLE
[BUG] OpenAPI specification example in documentation is false

### ISSUE THREAD

**Issue by javisst** [OpenManufacturingPlatform/sds-sdk#150]
**Describe the bug**
The documentation shows an example for OpenAPI generation which has the wrong switch for base-url. **-baseUrl** does not work. It should state **-base-url**.

_Incorrect_
```
java -jar bamm-cli-1.0.2.jar -i AspectModel.ttl -oapi-yaml -baseUrl "https://www.example.org"
-arp "/resources/{resourceId}" -apf fileLocation
```
_Correct_
```
java -jar bamm-cli-1.0.2.jar -i AspectModel.ttl -oapi-yaml -base-url "https://www.example.org"
-arp "/resources/{resourceId}" -apf fileLocation
```
**Where**
Documentation for version 1.0.2, 1.1.0-M1,1.1.0-M2,1.1.0-M3
https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/1.1.0-M3/tooling-guide/bamm-cli.html

**Comment by atextor** [comment]
This has been fixed on main (both the switch and the changed argument structure).
