### ISSUE TITLE
[BUG] bamm-cli build date is incorrect

### ISSUE THREAD

**Issue by benjaminbauer** [OpenManufacturingPlatform/sds-sdk#152]
In version 1.0.2 of the bamm-cli the build date is not correctly displayed. Looks like the variable is not resolved in the build process

```
❯ bamm-cli -v
Parsing arguments failed: The following option is required: [--input | -i]

BAMM Aspect Meta Model Command Line Tool
  Version: 1.0.2
  Build date: ${maven.build.timestamp}

```

**Comment by atextor** [comment]
This bug has been superseded, as the current version on `main` does not print the build version and date at all. Adding this back in is covered in #157.
