### ISSUE TITLE
[BUG] BAMM-CLI Maven plugin dependency not correctly managed

### ISSUE THREAD

**Issue by develobee** [OpenManufacturingPlatform/sds-sdk#161]
**Describe the bug**
We use the BAMM-CLI V1.1.0-M3 maven plugin for generation of our domain objects. This worked fine until the M4 version was released.
After that the M4 version was used. We had to explicitly set the M3 version in the plugin config to be able to use the M3 version again.

**Where**
Maven dependency management

**Screenshots**

**Additional context**

**Comment by atextor** [comment]
@develobee I think you need to explictly set a maven plugin's version either in the pom.xml where it is used, or in any of its transitive parent poms. How did you declare the plugin dependency in your local pom, how does the declaration (plugin or pluginManagement) in the respective parent(s) look like?

**Comment by develobee** [comment]
We tried to declare it in a transitive parent pom but there seem to be some problems with multi module projects. We decided to declare it right at the plugin dependency declaration. This works fine.
Either way it seems to be more of a maven problem then an SDK problem.
