### ISSUE TITLE
[Task] Milestone disclaimer in created models

### ISSUE THREAD

**Issue by chris-volk** [OpenManufacturingPlatform/sds-sdk#168]
Scope: Pretty Printer
When pretty printer is used to serialize an Aspect Model based on a milestone BAMM version, a "milestone disclaimer" is being created, similar to this:
"This model has been created by SDS SDK Version x and is not intended for productive usage."

Additionally, if easy: When pretty printing a productive version and there is a milestone disclaimer, the milestone disclaimer is removed.

**Comment by atextor** [comment]
I agree that having a hint in writing models based on a BAMM milestone version is useful. However, the message should reflect this and refer to the BAMM (artifact) version used, not to the SDS SDK version used to write the model out. The message should read something like:
> This model was created based on $bamm-artifact-version and is not intended for productive usage.
It should refer to _artifact's_ version, e.g. "2.0.0-M1".

**Comment by chris-volk** [comment]
Yes, absolutely correct, thank you.
