### ISSUE TITLE
[BUG] Entity without property generates non compilable java code

### ISSUE THREAD

**Issue by DvSmi** [OpenManufacturingPlatform/sds-sdk#184]
**Describe the bug**
Defining an Aspect with an Entity without any further Properties, and the Entity extending an AbstractEntity with a property, leads to an incorrect generation of the hashCode method.
```
@Override
public int hashCode() {
    return Objects.hash(
            super.hashCode(),
    );
```

**Comment by atextor** [comment]
Fixed by #185
