### ISSUE TITLE
[BUG] Attribute `bamm:parameters` of Event is ignored in Loader

### ISSUE THREAD

**Issue by NicoMakowe** [OpenManufacturingPlatform/sds-sdk#200]
**Describe the bug**
An Aspect Model that has an Event with at least one parameters, will not be loaded correctly. The loader searches for `bamm:properties` instead of `bamm:parameters`.

**Where**
sds-aspect-meta-model-java
https://github.com/bci-oss/sds-sdk/blob/main/core/sds-aspect-meta-model-java/src/main/java/io/openmanufacturing/sds/metamodel/loader/instantiator/EventInstantiator.java#L36

Test Model
https://github.com/bci-oss/sds-sdk/blob/main/core/sds-test-aspect-models/src/main/resources/valid/bamm_2_0_0/io.openmanufacturing.test/1.0.0/AspectWithEvent.ttl#L28

**Comment by atextor** [comment]
Fixed in #204
