### ISSUE TITLE
[BUG] Example Values in generated HTML Doucmentation (CLI) not displayed correctly

### ISSUE THREAD

**Issue by BirgitBoss** [OpenManufacturingPlatform/sds-sdk#211]
**Describe the bug**
When generating the documentation

```
DefaultScalarValue[value=2022-03-11, typeUri='DefaultScalar[metaModelVersion=BAMM_2_0_0, urn='http://www.w3.org/2001/XMLSchema#date']']
```

for a .ttl with

```
      <urn:bamm:io.openmanufacturing:meta-model:1.0.0#exampleValue>
                "2022-03-11"^^<http://www.w3.org/2001/XMLSchema#date> ;
```
Expectation:

  Value displayed in documentation is just "2022-03-11".

**Where**
CLI generate HTML documentation for BAMM model

**Screenshots**

![grafik](https://user-images.githubusercontent.com/59824205/184883904-6019c46e-6610-4d8c-a7b2-d87d69a5522f.png)

**Comment by waltersve** [comment]
Hi @BirgitBoss, can confirm the problem. I will discuss it with the dev team. I keep you posted about the result.
