### ISSUE TITLE
[BUG] Generated HTML Documentation contains unconnected Timestamp Characteristic

### ISSUE THREAD

**Issue by bs-jokri** [OpenManufacturingPlatform/sds-sdk#214]
**Describe the bug**
There is a model with no timestamp defined. However, the generated html output from the bamm sdk (v2.0.2) contains a unconnected Timestamp Characteristic definition

**Where**
command to generate model
java -jar .BAMMCLI/bamm-cli-2.0.2.jar aspect modelName.ttl to html -o result.html

**Screenshots**
<img width="396" alt="image" src="https://user-images.githubusercontent.com/13886571/186649684-d422b224-0065-435b-9260-0b76ee3a64a3.png">

**Additional context**
Model can be provided upon request.

**Comment by waltersve** [comment]
Hi @bs-jokri, the issue should be fixed with the change https://github.com/OpenManufacturingPlatform/sds-sdk/pull/215. To finally verify that, could you please provide the model or an example model?

**Comment by atextor** [comment]
As mentioned by @waltersve, this should be fixed. @bs-jokri if you can still reproduce it, please add a model that triggers it and reopen the issue.
