### ISSUE TITLE
[BUG] OpenAPI generation - No description available

### ISSUE THREAD

**Issue by horstholz** [OpenManufacturingPlatform/sds-sdk#231]
**Describe the bug**
On the generation of an OpenAPI from an Aspect Model the description of the characteristic is missing.

**Where**
AME, AME SDK

**Screenshots**
The "description" is missing in the OpenAPI and in the JSON Schema:
![image](https://user-images.githubusercontent.com/109132916/193294366-a47b8022-2f16-4b27-aa18-ec7483620c53.png)

**Comment by atextor** [comment]
Fixed in #242
