### ISSUE TITLE
[BUG] Java code generation fails when an abstract entity contains only abstract properties

### ISSUE THREAD

**Issue by kaniyan** [OpenManufacturingPlatform/sds-sdk#254]
**Describe the bug**
Java code generation fails when an abstract entity contains only abstract properties.

**Where**
In the above scenario, the `equals` method in java code generated using velocity template is incomplete and leads to syntax error.

**Screenshots**
![image](https://user-images.githubusercontent.com/18659982/200604615-a9165c32-5bb6-4c1f-9117-27dcf873b1db.png)

**Comment by atextor** [comment]
Fixed by #255
