### ISSUE TITLE
Steps for executing BAMM CLI jar

### ISSUE THREAD

**Issue by ramdinavahi** [OpenManufacturingPlatform/sds-sdk#51]
Currently we were able to build the jar skipping the Unit test as the build failed for few test cases.

![sds-sdk build](https://user-images.githubusercontent.com/42441708/141413847-cecacf95-08e2-4236-8d55-df42acacc095.png)
@michelu89 
Is there any documentation on how to execute the jar with right input parameters/arguments?
We were getting below error while executing the JAR file:
**Exception in thread "main" java.lang.NullPointerException: inStream parameter is null**

We expect a clean build without errors and understand the required input parameters to run the JAR and some steps required to use the BAMM

**Comment by atextor** [comment]
Hello @ramdinavahi,
please open a separate issue for each problem the next time.
Regarding your screenshot and problems building, please supply information about which version of you are trying to build (main branch, tag or other commit), your used JDK, operating system and other helpful context information, such as how many and/or which tests are failing.
Regarding bamm-cli documentation, please see the documentation here: https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html

**Comment by ramdinavahi** [comment]
Hello @atextor 
Currently I am unable to access the bamm-cli-1.0.0.jar on https://openmanufacturingplatform.github.io/sds-documentation/sds-developer-guide/dev-snapshot/tooling-guide/bamm-cli.html
Do you already have jar ready or  let us know when will it be available for download on the website?

**Comment by eriksven** [comment]
Hello @ramdinavahi , 

sorry for the late reply. The BAMM CLI is available under Releases in GitHub. In the meantime we release the BAMM CLI 1.0.1 which is available in https://github.com/OpenManufacturingPlatform/sds-sdk/releases/tag/v1.0.1

**Comment by atextor** [comment]
Hello @ramdinavahi,
the link in the developer documentation was broken, as described here: #71 
In the meantime, you can follow @eriksven's suggestion and directly download the artifact from the Github release. If this solves your problem, feel free to close the issue :+1:

**Comment by ramdinavahi** [comment]
The release information helped
