### ISSUE TITLE
[Task] Java Code Generation make Copyright notice optional

### ISSUE THREAD

**Issue by eriksven** [OpenManufacturingPlatform/sds-sdk#59]
**Is your task related to a problem? Please describe.**
When using the code generation for an Aspect, for example with -java in the BAMM CLI, the code contains a copyright notice which not be applicable. 

**Describe the solution you'd like**
I would see that the addition of the copyright is not happening in the default case. The user should still have the option to specify a custom copyright notice. 

**Describe alternatives you've considered**
Removing the copyright notice completly would be an alternative. But there are situations where one wants to specify some sort of copyright notice. 

**Additional context**
None

**Comment by georgschmidtdumont** [comment]
Labelled as bug since the current implementation generates an incorrect copyright notice, i.e. header.
