### ISSUE TITLE
Using a Characteristic as data-type is deemed valid by BAMM validator

### ISSUE THREAD

**Issue by georgschmidtdumont** [OpenManufacturingPlatform/sds-sdk#6]
**Describe the Bug**
Using a Characteristic as the data-type of another Characteristic is deemed valid by the Aspect Model validator. However, this is not valid and the Aspect Model validation should produce a corresponding validation report.

**Comment by atextor** [comment]
This is actually a bug in the meta model (in the SHACL shapes that describe what and how is validated). I created a corresponding issue there: https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model/issues/73
