### ISSUE TITLE
[BUG] Antora version not correctly set for v1.0.1 tagged version

### ISSUE THREAD

**Issue by eriksven** [OpenManufacturingPlatform/sds-sdk#66]
**Describe the bug**
In the https://github.com/OpenManufacturingPlatform/sds-sdk/blob/v1.0.1/documentation/developer-guide/antora.yml the version field is not set correctly for the Tag v1.0.1 . This leads to a break in the Antora build for example in the SDS Documentation ( for example https://github.com/OpenManufacturingPlatform/sds-documentation/runs/4297515596?check_suite_focus=true)

**Where**
As indicated above https://github.com/OpenManufacturingPlatform/sds-sdk/blob/v1.0.1/documentation/developer-guide/antora.yml 

**Screenshots**
Not applicable.

**Comment by atextor** [comment]
This has been fixed in #68.
