### ISSUE TITLE
Support 'extends' in the SDK

### ISSUE THREAD

**Issue by georgschmidtdumont** [OpenManufacturingPlatform/sds-sdk#7]
**Is your task related to a problem? Please describe.**

In the issue [Introduce Entity inheritance](https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model/issues/34) the concept of extending Entities is introduced in BAMM. To allow developers to use Aspect Models with this new concept in their applications or services, the SDK must support `extends`.

**Comment by atextor** [comment]
Fixed by PR #10.
