### ISSUE TITLE
[BUG] Sample Projects

### ISSUE THREAD

**Issue by fatadel** [OpenManufacturingPlatform/sds-sdk#75]
It is mentioned that the project structure contains `samples` folder containing "sample projects to get you started quickly". However, I don't see this folder. Neither initially, nor after building.

https://github.com/OpenManufacturingPlatform/sds-sdk/blob/97f057f241969c1a05afb3e93b8967fbd23da2ec/README.md?plain=1#L76

**Comment by atextor** [comment]
This repository does indeed currently not include samples. This should be fixed in the readme.
